import { defineConfig } from 'vite'

const fullReloadAlways = {
    name: 'full-reload',
    handleHotUpdate({ server }) {
        server.ws.send({ type: 'full-reload' })
        return []
    },
}

export default defineConfig(({ command, mode }) => {
    // NOTE: blueprint-URL imports hit a server-side CORS proxy at `/corsproxy`
    // (a Cloudflare Pages Function, `functions/corsproxy.js`). It doesn't run on
    // this fork's GitHub Pages deploy, and we no longer proxy dev to an external
    // host's proxy, so URL imports are inert here until the fork hosts its own —
    // see https://github.com/trisiak/factorio-blueprint-editor/issues/17. Paste /
    // raw `?source=<bpstring>` import still works.
    const proxy = {}
    if (mode !== 'production') {
        proxy['/data'] = {
            target: 'http://127.0.0.1:8081',
            rewrite: path => path.replace(/^\/data/, ''),
        }
    }
    // Sub-path deploys (e.g. GitHub Pages at /factorio-blueprint-editor/, or a
    // per-PR preview under /pr-preview/pr-N/) set PUBLIC_BASE. Defaults to '/'
    // so a root-path deploy and local dev are unchanged.
    let base = process.env.PUBLIC_BASE ?? '/'
    if (!base.endsWith('/')) base += '/'

    // Where the editor fetches each pack's data.json + *.basis atlas from.
    //
    // The pack data no longer lives in this repo and is no longer copied into
    // `dist/`: it is generated by the Rust exporter and published by the
    // dedicated data plane, `trisiak/factorio-pack-data` (GitHub Pages, served
    // with `Access-Control-Allow-Origin: *`, so the cross-origin fetch needs no
    // proxy). Builds therefore never touch `packages/exporter/data/output/` and
    // don't depend on it existing.
    //
    // Precedence:
    //   1. VITE_DATA_URL — explicit, wins everywhere. Both Pages workflows and
    //      the e2e webServer set it (pinning the host at the call site rather
    //      than relying on this default).
    //   2. `vite build` with no override → the public data plane, so a bare
    //      `npm run build:website` yields a site that actually renders.
    //   3. `vite` (dev) → `<base>data`, which the dev-server proxy above
    //      forwards to the exporter's :8081, so the dev flow keeps rendering
    //      whatever you just regenerated locally (`npm run serve:data`, or the
    //      server the exporter starts when a run finishes).
    const DATA_PLANE_URL = 'https://trisiak.github.io/factorio-pack-data'
    const dataUrl =
        process.env.VITE_DATA_URL ?? (command === 'build' ? DATA_PLANE_URL : `${base}data`)

    const plugins = []
    if (command !== 'build') plugins.push(fullReloadAlways)

    return {
        base,
        define: { __DATA_URL__: JSON.stringify(dataUrl) },
        build: { sourcemap: true },
        preview: { port: 8080 },
        server: {
            port: 8080,
            proxy,
        },
        plugins,
    }
})
